### ISSUE TITLE
「【依頼】最終課題挙動確認」

### ISSUE THREAD

**Issue by masaaki1130** [masaaki1130/fleamarket_sample_78e#53]
■ Basic認証
ID：masaaki
Pass：hayate1130

■ テスト用アカウント
◯ 購入者用
メールアドレス：test2@gmail.com
パスワード：aaaaaaa

◯ 購入用カード情報
番号：4242424242424242
期限：4/26
セキュリティカード：123

◯ 出品者用
メールアドレス：test@gmail.com
パスワード：aaaaaaa

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂いたところ、以下の項目の不備が見受けられましたので修正をお願いします！

> ■ URL
> IPアドレス：
> Github（最終課題のリポジトリ）：

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by masaaki1130** [comment]
すいません。抜けておりました。
修正いたしました。
■ URL
IPアドレス：54.238.23.37
Github（最終課題のリポジトリ）：https://github.com/masaaki1130/fleamarket_sample_78e.git

■ Basic認証
ID：masaaki
Pass：hayate1130

■ テスト用アカウント
◯ 購入者用
メールアドレス：test2@gmail.com
パスワード：aaaaaaa

◯ 購入用カード情報
番号：4242424242424242
期限：4/26
セキュリティカード：123

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正箇所]**
**○Issuesに「 出品者用メールアドレス：及びパスワード：」の記入もお願いします。**

**○出品内容（漫画・自転車アクセサリー）に対して販売価格が高額に設定されている為、実際のフリマアプリに出品されている様なものを出品しましょう。**

修正し次第、以下の最終課題完了報告フォームを再度ご提出して下さい！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by masaaki1130** [comment]
■ URL
IPアドレス：54.238.23.37
Github（最終課題のリポジトリ）：https://github.com/masaaki1130/fleamarket_sample_78e.git

■ Basic認証
ID：masaaki
Pass：hayate1130

■ テスト用アカウント
◯ 購入者用
メールアドレス：test2@gmail.com
パスワード：aaaaaaa

◯ 購入用カード情報
番号：4242424242424242
期限：4/26
セキュリティカード：123

◯ 出品者用
メールアドレス：test@gmail.com
パスワード：aaaaaaa

**Comment by mutorisa** [comment]
再度ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。**
